---
name: Darcs-Inventory
version: 1.0.1
author:
  - 'David Caldwell <david@porkrind.org>'
abstract: Read and parse a darcs version 1 or 2 inventory file
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Digest::SHA1: 0
  Time::Local: 0
provides:
  Darcs::Inventory:
    file: lib/Darcs/Inventory.pm
    version: 1.0.1
  Darcs::Inventory::Diff:
    file: lib/Darcs/Inventory/Diff.pm
  Darcs::Inventory::Patch:
    file: lib/Darcs/Inventory/Patch.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
